psql_host=$1
psql_port=$2
db_name=$3
psql_user=$4
psql_password=$5


if [ $# -ne 5 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

# Saving system output
vm_cpu_out=$(vmstat --unit M)
lscpu_out=$(lscpu)
vm_disk_out=$(vmstat --unit M -d)
df_disk_out=$(df -BM /)
timestamp=$(date --utc -u '+%Y-%m-%d %H:%M:%S')

# Constructing input values
hostname=$(hostname -f)
cpu_number=$(echo "$lscpu_out"  | egrep "^CPU\(s\):" | awk '{print $2}' | xargs)
cpu_architecture=$(echo "$lscpu_out"  | egrep "^Architecture:" | awk '{print $2}' | xargs)
cpu_model=$(echo "$lscpu_out"  | egrep "^Model:" | awk '{print $2}' | xargs)
cpu_mhz=$(echo "$lscpu_out"  | egrep "^CPU MHz" | awk '{print $3}' | xargs)
l2_cache=$(echo "$lscpu_out"  | egrep "^L2" | awk '{print $3}' | sed 's/K//' |xargs)
total_mem=$(echo "$vm_cpu_out" | tail -1 | awk '{print $4}')
timestamp=$(date --utc -u '+%Y-%m-%d %H:%M:%S')

# Finding autogenerated id from table
host_id="(SELECT id FROM host_info WHERE hostname='$hostname');"

insert_statement="INSERT INTO 
host_info(hostname, cpu_number, cpu_architecture, cpu_model, cpu_mhz, l2_cache, timestamp, total_mem) 
VALUES ('$hostname', $cpu_number, '$cpu_architecture', '$cpu_model', $cpu_mhz, $l2_cache, '$timestamp', $total_mem);"

#set up env var for pql cmd
export PGPASSWORD=$psql_password 
#Insert date into a database
psql -h $psql_host -p $psql_port -d $db_name -U $psql_user -c "$insert_statement"
exit $?