psql_host=$1
psql_port=$2
db_name=$3
psql_user=$4
psql_password=$5


if [ $# -ne 5 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

# Saving system output
vm_cpu_out=$(vmstat --unit M)
lscpu_out=$(lscpu)
vm_disk_out=$(vmstat --unit M -d)
df_disk_out=$(df -BM /)
timestamp=$(date --utc -u '+%Y-%m-%d %H:%M:%S')

# Constructing input values
hostname=$(hostname -f)
memory_free=$(echo "$vm_cpu_out" | tail -1 | awk -v col="4" '{print $col}')
cpu_idle=$(echo "$vm_cpu_out" | tail -1 | awk -v col="15" '{print $col}')
cpu_kernel=$(echo "$vm_cpu_out" | tail -1 | awk -v col="14" '{print $col}')
disk_io=$(echo "$vm_disk_out"| tail -1 | awk -v col="10" '{print $col}')
disk_available=$(echo "$df_disk_out"| tail -1 | awk -v col="4" '{print $col}' | sed 's/M//')

# Finding autogenerated id from table
host_id="(SELECT id FROM host_info WHERE hostname='$hostname')"

insert_statement="INSERT INTO host_usage(timestamp,host_id,memory_free,cpu_idle,cpu_kernel,disk_io,disk_available) VALUES ('$timestamp',$host_id,$memory_free,$cpu_idle,$cpu_kernel,$disk_io,$disk_available);"

#set up env var for pql cmd
export PGPASSWORD=$psql_password 
#Insert date into a database
psql -h $psql_host -p $psql_port -d $db_name -U $psql_user -c "$insert_statement"
exit $?